baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'jgennari.github.io'
theme = "hugo-theme-monochrome"
sectionPagesMenu = 'main'


[params]
footer = "Copyright © 2023 | joey@gennari.com"
color_scheme = "dark" 

[[menu.navbar]]
identifier = "about"
name = "about"
title = "about"
url = "/about/"
weight = 100

[[menu.navbar]]
identifier = "series"
name = "series"
url = "/series/"
weight = -100

[[menu.navbar]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 80